### ISSUE TITLE
Create skeleton CKAN extension

### ISSUE THREAD

**Issue by pwalsh** [okfn/example-rockfound#1]
# Description 

Customisation of CKAN is done via Extensions. As we move from a vanilla CKAN install to one with custom functionality, we need our own extension that will provide a home for our custom code.

# Tasks

- [ ] Implement skeleton extension which will hold all rockbound custom code. There is extensive [documentation to follow](http://docs.ckan.org/en/latest/extensions/index.html).
- [ ] Write a basic test to validate a dummy function, simply to get the test flow working. There is [good documentation](http://docs.ckan.org/en/latest/extensions/testing-extensions.html).
- [ ] Set up continuous integration to run tests automatically as the codebase develops. Use [Travis CI](https://travis-ci.org), and you can refer to an example configuration for Travis CI [here](https://github.com/ckan/ckanext-pages/blob/master/.travis.yml). If you use your own internal CI server/workflow, adjust to suit.

## Requires

- Estimate from implementor
