### ISSUE TITLE
Core security, stability, and infrastructure extensions

### ISSUE THREAD

**Issue by pwalsh** [okfn/example-rockfound#4]
# Description

We've identified a core set of extensions that we want enabled on our instance of CKAN, that deal with security, authentication, stability and infrastructure concerns. These should be enabled by default as part of our base CKAN setup

# Tasks

- [ ] Implement the [security](https://github.com/data-govt-nz/ckanext-security) extension.
- [ ] OKTA support can be implemented via the existing [SAML extension](https://github.com/DataShades/ckanext-saml2).
- [ ] The [cloud storage](https://github.com/TkTech/ckanext-cloudstorage) extension can be used to deploy S3 as the file storage backend for CKAN.
- [ ] Ensure that S3 is used for all file storage, and that user sessions are saved in the database
- [ ] Ensure these extensions are installed by default as part of all our CKAN usage
- [ ] Test the configuration changes in local development
- [ ] Push changes to the production infrastructure

## Requires

- No dependencies
