### ISSUE TITLE
Basic theme tweaks for brand alignment

### ISSUE THREAD

**Issue by pwalsh** [okfn/example-rockfound#5]
# Description

At this stage of the project, we are not doing extension UI/X customisation. However, we can take advantage of some simple hooks that CKAN provides to change aspects of the default theme to be more aligned with our brand, in terms of logo and primary brand palette.

# Tasks

- [ ] Get minimal brand assets required (logo, colours as HEX)
- [ ] Review CKAN [options for theming](http://docs.ckan.org/en/latest/maintaining/configuration.html#front-end-settings).
- [ ] Configure the custom extension to set the values for our theme customisation by default on our instance of CKAN

## Requires

- No dependencies
